// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxdehqmktczpckxqzmzn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4ZGVocW1rdGN6cGNreHF6bXpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNzc1NzYsImV4cCI6MjA2MjY1MzU3Nn0.U9pXCCe1_g64uHODz2_I82-qMyb6J9t3wjuP01oFevo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);